[package]
name = "yasync"
version = "0.1.0"
edition = "2021"


[dependencies]
google-photoslibrary1 = "*"
reqwest = "0.12.4"
serde = "^1.0"
serde_json = "^1.0"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
